name = "ThreadedScansBenchmarks"
uuid = "9d4e69ce-ab08-41b0-abf7-c5484e6143ec"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ThreadedScans = "24d252fe-5d94-4a69-83ea-56a14333d47a"

[compat]
julia = "1"
